"use client";

import {
  type CSSProperties,
  type ReactNode,
  useCallback,
  useEffect,
  useRef,
  useState,
} from "react";
import { useRouter } from "next/navigation";

import { OVERVIEW_TAB } from "./EntryTabs";
import styles from "./GuidedTour.module.css";

type TourStep = {
  /** A CSS selector for the element the step highlights. */
  target: string;
  /** The tab the target lives on, or null when it is on every tab. */
  tab: string | null;
  /** Shown only with this Structure viewer; omitted means with either. */
  viewer?: "hetstar" | "plain";
  title: string;
  subtitle: string;
  body: ReactNode;
};

const HETSTAR_DOCS_URL = "https://github.com/rtviii/hetstar#readme";

const STEPS: TourStep[] = [
  {
    target: '[data-tour="identity"]',
    tab: OVERVIEW_TAB,
    title: "Entry and experimental dataset",
    subtitle: "Experimental data associated with this entry",
    body: "Each entry begins with an experimental dataset, identified here by its PDB accession when available. The underlying experimental observations remain fixed. The models on this page are different structural interpretations of those same data.",
  },
  {
    target: '[data-tour="rail"]',
    tab: OVERVIEW_TAB,
    title: "Model set",
    subtitle: "Models derived from the same experimental dataset",
    body: "Each row represents a model derived from the same experimental dataset. This may include the deposited PDB structure, a re-refinement, or a model generated by another analysis method. Select a model to inspect it throughout the entry. Use the metric controls to sort and compare models quantitatively.",
  },
  {
    target: '[data-tour="evaluations"]',
    tab: OVERVIEW_TAB,
    title: "Model evaluation",
    subtitle: "Metrics for comparing model quality and fit",
    body: "Evaluation metrics show how the selected model compares with other models of the same dataset. These values provide quantitative evidence about model quality and agreement with the experimental data. At present, reported metrics are inherited from the model source rather than recomputed by Dynamic PDB.",
  },
  {
    target: '[data-tour="structure"]',
    tab: "structure",
    viewer: "plain",
    title: "Structure view",
    subtitle: "Atomic coordinates and conformational states",
    body: "The Structure view displays the atomic coordinates of the selected model. Rotate, zoom, and inspect the structure directly. When a model contains alternative conformations or multiple structural states, they can be represented and examined here.",
  },
  {
    target: ".hetstar",
    tab: "structure",
    viewer: "hetstar",
    title: "Heterogeneity viewer",
    subtitle: "Conformational heterogeneity against the experimental data",
    body: (
      <>
        The Structure view opens{" "}
        <a href={HETSTAR_DOCS_URL} target="_blank" rel="noreferrer">
          hetstar
        </a>
        , a viewer for conformational heterogeneity. Where available, Model A
        is the qFit multiconformer model, otherwise an ensemble or the deposited
        model. Model B is the deposited model, drawn as a toggleable ghost for
        comparison. When no qFit model is available, the deposited model is
        shown on its own. When no mmCIF data is available, the heterogeneity
        viewer is not used. This is in active development.
      </>
    ),
  },
  {
    target: ".hetstar aside",
    tab: "structure",
    viewer: "hetstar",
    title: "Entry summary",
    subtitle: "Experimental context and alternate conformers",
    body: "The side panel summarizes the entry and the loaded model: resolution, space group, temperature, pH, and R-work / R-free, along with residue and atom counts, the number of residues modeled with alternate conformations, and bound ligands and ions.",
  },
  {
    target: ".hetstar .right-2.top-2",
    tab: "structure",
    viewer: "hetstar",
    title: "Electron density and display",
    subtitle: "Maps computed in the browser from the deposited structure factors",
    body: "2Fo-Fc and Fo-Fc maps are calculated in the browser from the deposited structure factors and load in the background. Toggle density to display them, with Fo-Fc contoured at +3\u03c3 (green) and -3\u03c3 (red). Per-residue metrics can be painted onto the density surface, and the style controls set representation, coloring, and B-factor display.",
  },
  {
    target: ".hetstar aside + div",
    tab: "structure",
    viewer: "hetstar",
    title: "Residue-level inspection",
    subtitle: "Alternate conformers and their support in the density",
    body: "Model A is collapsed to its highest-occupancy conformer by default. Click a residue to expand its alternate conformers and inspect their occupancies, mean B-factors, and support in the experimental density. Selections can be clipped, measured, and bookmarked for later comparison.",
  },
  {
    target: ".hetstar > div > div:last-child",
    tab: "structure",
    viewer: "hetstar",
    title: "Sequence lanes",
    subtitle: "Per-residue heterogeneity metrics along the chain",
    body: "The lanes below the canvas show one chain at a time, with secondary structure, PDBe domain and modification annotations, and ligand contacts. Metric lanes plot per-residue values such as conformer count, occupancy entropy, mean B-factor, RMSF, and Fo-Fc statistics. Hovering or selecting here is linked to the 3D view.",
  },
  {
    target: '[data-tour="experiment"]',
    tab: "experiment",
    title: "Experimental metadata",
    subtitle: "Conditions under which the structural data were collected",
    body: "The Experiment view records the conditions under which the structural data were collected, including temperature, pH, crystal form (space group), and other experimental metadata, along with data quality measures such as resolution. These conditions can influence the structural states that are observed. For example, cryogenic cooling can suppress motions that may remain visible at room temperature.",
  },
  {
    target: '[data-tour="sequence"]',
    tab: "sequence",
    title: "Residue-level data",
    subtitle: "Sequence-linked measurements and comparisons",
    body: "The Sequence view aligns model information with individual residues in the protein chain. Per-residue measurements can therefore be interpreted in their sequence and structural context. Related entries for the same protein are shown below, enabling comparison of the same molecule across experiments, conditions, and models.",
  },
  {
    target: '[data-tour="download"]',
    tab: null,
    title: "Data access",
    subtitle: "Files associated with the selected model",
    body: "Dynamic PDB is designed as open scientific infrastructure. Download the files associated with the selected model for independent analysis, comparison, or reuse in other computational workflows.",
  },
];

// Survives the navigation between tabs, and between the entry and model
// routes, which render different pages and so remount the tour.
const STORAGE_KEY = "dpdb-tour-step";
// A tab's content streams in after the navigation; past this, the card is
// shown without a highlight rather than waiting forever.
const FIND_TIMEOUT_MS = 4000;
const GAP = 14;
const PAD = 6;

type Rect = { top: number; left: number; width: number; height: number };

/**
 * A step-by-step walk through the entry page.
 *
 * Steps point at elements by selector, mostly `data-tour` markers; the
 * heterogeneity viewer is vendored, so its steps use its own markup. Each step
 * names the tab it lives on, so the tour can move the reader between tabs by
 * URL, the same way the tab strip does. Steps on tabs this entry does not have,
 * or for the viewer it does not use, are skipped.
 */
export default function GuidedTour({
  base,
  tabs,
  hetstar,
}: {
  /** The scope's own path, as given to the tab strip. */
  base: string;
  /** The ids of the tabs this entry offers. */
  tabs: string[];
  /** Whether the Structure tab opens the heterogeneity viewer. */
  hetstar: boolean;
}) {
  const router = useRouter();
  const viewer = hetstar ? "hetstar" : "plain";
  const steps = STEPS.filter(
    (step) =>
      (step.tab === null || tabs.includes(step.tab)) &&
      (step.viewer === undefined || step.viewer === viewer),
  );
  const [index, setIndex] = useState<number | null>(null);
  const [rect, setRect] = useState<Rect | null>(null);
  const [cardSize, setCardSize] = useState({ width: 380, height: 240 });
  const card = useRef<HTMLDivElement>(null);
  const next = useRef<HTMLButtonElement>(null);

  // Start from a `?tour=1` link, or resume a tour that was in progress before
  // a remount.
  useEffect(() => {
    // Once, on mount: after that the tour keeps its own place.
    const url = new URL(window.location.href);
    if (url.searchParams.get("tour") === "1") {
      url.searchParams.delete("tour");
      window.history.replaceState(window.history.state, "", url);
      window.sessionStorage.setItem(STORAGE_KEY, "0");
      setIndex(0);
      return;
    }
    const saved = window.sessionStorage.getItem(STORAGE_KEY);
    if (saved !== null && Number(saved) < steps.length) {
      setIndex(Number(saved));
    }
  }, []);

  const go = useCallback(
    (to: number | null) => {
      if (to === null || to < 0 || to >= steps.length) {
        window.sessionStorage.removeItem(STORAGE_KEY);
        setIndex(null);
        setRect(null);
        return;
      }
      window.sessionStorage.setItem(STORAGE_KEY, String(to));
      setRect(null);
      setIndex(to);
    },
    [steps.length],
  );

  const step = index !== null ? steps[index] : null;

  // Move to the step's tab when it is not the one on screen.
  useEffect(() => {
    if (!step || step.tab === null) {
      return;
    }
    const current = new URLSearchParams(window.location.search).get("tab") ?? OVERVIEW_TAB;
    if (current !== step.tab) {
      router.push(step.tab === OVERVIEW_TAB ? base : `${base}?tab=${step.tab}`, {
        scroll: false,
      });
    }
  }, [step, base, router]);

  // Follow the target every frame while the tour is open: the page scrolls,
  // the viewer loads, and the tab content arrives after the step changes.
  useEffect(() => {
    if (!step) {
      return;
    }
    const started = performance.now();
    let scrolled = false;
    let frame = 0;
    const track = () => {
      const target = document.querySelector<HTMLElement>(step.target);
      if (target) {
        if (!scrolled) {
          target.scrollIntoView({ block: "center", behavior: "smooth" });
          scrolled = true;
        }
        const box = target.getBoundingClientRect();
        setRect((prev) =>
          prev &&
          prev.top === box.top &&
          prev.left === box.left &&
          prev.width === box.width &&
          prev.height === box.height
            ? prev
            : { top: box.top, left: box.left, width: box.width, height: box.height },
        );
      } else if (performance.now() - started > FIND_TIMEOUT_MS) {
        setRect(null);
      }
      frame = window.requestAnimationFrame(track);
    };
    frame = window.requestAnimationFrame(track);
    return () => window.cancelAnimationFrame(frame);
  }, [step]);

  useEffect(() => {
    if (!card.current) {
      return;
    }
    const { width, height } = card.current.getBoundingClientRect();
    setCardSize((prev) =>
      prev.width === width && prev.height === height ? prev : { width, height },
    );
  });

  useEffect(() => {
    next.current?.focus({ preventScroll: true });
  }, [index]);

  useEffect(() => {
    if (index === null) {
      return;
    }
    // The page stays live under the tour, so the arrows only step it while the
    // card has focus; anywhere else they belong to the viewer or the page.
    const onKeyDown = (event: KeyboardEvent) => {
      const inCard = card.current?.contains(document.activeElement) ?? false;
      if (event.key === "Escape") {
        go(null);
      } else if (!inCard) {
        return;
      } else if (event.key === "ArrowRight") {
        go(index + 1);
      } else if (event.key === "ArrowLeft" && index > 0) {
        go(index - 1);
      }
    };
    document.addEventListener("keydown", onKeyDown);
    return () => document.removeEventListener("keydown", onKeyDown);
  }, [index, go]);

  return (
    <>
      <button type="button" className={styles.start} onClick={() => go(0)}>
        <svg
          width="14"
          height="14"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
          aria-hidden="true"
        >
          <circle cx="12" cy="12" r="9" />
          <path d="m15.5 8.5-2 5-5 2 2-5z" />
        </svg>
        Take the tour
      </button>

      {step && index !== null ? (
        <>
          {rect ? (
            <div
              className={styles.spotlight}
              style={{
                top: rect.top - PAD,
                left: rect.left - PAD,
                width: rect.width + PAD * 2,
                height: rect.height + PAD * 2,
              }}
            />
          ) : null}
          <div
            ref={card}
            className={styles.card}
            role="dialog"
            aria-labelledby="guided-tour-title"
            style={place(rect, cardSize)}
          >
            <p className={styles.count}>
              {index + 1} of {steps.length}
            </p>
            <h2 id="guided-tour-title" className={styles.title}>
              {step.title}
            </h2>
            <p className={styles.subtitle}>{step.subtitle}</p>
            <p className={styles.body}>{step.body}</p>
            <div className={styles.actions}>
              <button type="button" className={styles.skip} onClick={() => go(null)}>
                Close
              </button>
              {index > 0 ? (
                <button type="button" className={styles.back} onClick={() => go(index - 1)}>
                  Back
                </button>
              ) : null}
              <button
                ref={next}
                type="button"
                className={styles.next}
                onClick={() => go(index + 1)}
              >
                {index === steps.length - 1 ? "Done" : "Next"}
              </button>
            </div>
          </div>
        </>
      ) : null}
    </>
  );
}

/**
 * Where the card goes: below the target, above it, then beside it, whichever
 * fits first. A target that fills the screen (the viewer, the rail) leaves no
 * room on any side, so the card then sits in the bottom corner over it.
 */
function place(
  rect: Rect | null,
  size: { width: number; height: number },
): CSSProperties {
  const vw = window.innerWidth;
  const vh = window.innerHeight;
  const clampX = (x: number) => Math.min(Math.max(x, GAP), vw - size.width - GAP);
  const clampY = (y: number) => Math.min(Math.max(y, GAP), vh - size.height - GAP);

  if (!rect) {
    return { top: (vh - size.height) / 2, left: (vw - size.width) / 2 };
  }
  const bottom = rect.top + rect.height + PAD;
  const right = rect.left + rect.width + PAD;
  if (bottom + GAP + size.height < vh) {
    return { top: bottom + GAP, left: clampX(rect.left) };
  }
  if (rect.top - PAD - GAP - size.height > 0) {
    return { top: rect.top - PAD - GAP - size.height, left: clampX(rect.left) };
  }
  if (right + GAP + size.width < vw) {
    return { top: clampY(rect.top), left: right + GAP };
  }
  if (rect.left - PAD - GAP - size.width > 0) {
    return { top: clampY(rect.top), left: rect.left - PAD - GAP - size.width };
  }
  return { top: vh - size.height - GAP * 2, left: vw - size.width - GAP * 2 };
}
