[flyway]
outOfOrder = true

[flyway.postgresql]
transactional.lock = false

[environments.local]
user = "postgres"
password = "password"
url = "jdbc:postgresql://localhost:35432/dynamic_pdb_local?sslmode=disable&timezone=UTC"
