apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "dynamic-pdb.fullname" . }}
  labels:
    {{- include "dynamic-pdb.labels" . | nindent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: {{ printf "%s-%s@kubernetescrd" .Release.Namespace (include "dynamic-pdb.stripApiPrefixName" .) | quote }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "dynamic-pdb.backendName" . }}
                port:
                  name: http
          - path: /install.sh
            pathType: Exact
            backend:
              service:
                name: {{ include "dynamic-pdb.s3proxyName" . }}
                port:
                  name: http
          - path: /releases
            pathType: Prefix
            backend:
              service:
                name: {{ include "dynamic-pdb.s3proxyName" . }}
                port:
                  name: http
          - path: /config
            pathType: Prefix
            backend:
              service:
                name: {{ include "dynamic-pdb.s3proxyName" . }}
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "dynamic-pdb.websiteName" . }}
                port:
                  name: http
