apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dynamic-pdb
  labels:
    {{- include "dynamic-pdb.labels" . | nindent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: "{{ .Release.Namespace }}-dynamic-pdb-strip-api-prefix@kubernetescrd"
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: dynamic-pdb-backend
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dynamic-pdb-website
                port:
                  name: http
