apiVersion: v1
kind: Service
metadata:
  name: dynamic-pdb-website
  labels:
    {{- include "dynamic-pdb.labels" . | nindent 4 }}
    {{- include "dynamic-pdb.website.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.website.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dynamic-pdb.website.selectorLabels" . | nindent 4 }}
